### ISSUE TITLE
Energy conversion

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#14]
My code for energy conversion relies on the non-linear `DataAxis` that is not part of the HyperSpy release yet, but might hopefully become a pre-release soon. Should I still contribute it here already for you to use with the right hyperspy development branch?

It contains some additional features like a wavelength dependent refractive index of air based on an analytical function (therefore it can not be a `FunctionalDataAxis`)

**Comment by jordiferrero** [comment]
I was thinking about this yesterday too.
If we do develop the code now relying on the `non-linear-axes` Hyperspy branch, it is quite tedious to add it as a dependency in the `setup.py` file (because upon installation it would git clone the branch and then install it, which takes longer than just using pip install the released versions).

Therefore I see two options:

1. To create a `dev` branch in lumispy (until Hyperspy adds the functionality)
2. To add it as the `master` branch and clarify in the docstring that it relies on the hyperspy dependency which is in development.

I am happy with both, as lumispy is in a very early stage. Feel free to decide 1 or 2 and contribute!

**Comment by jlaehne** [comment]
I also think both are good options. The second might be a little easier for us to handle so that we don't always have to switch branches in lumispy also (in HyperSpy I basically live in the non-linear-axis branch for more than a year already). I'll try to find some time in the next days to add that.

**Comment by jordiferrero** [comment]
@jlaehne What is the best way to ensure that anyone using LumiSpy works with the non-linear-axis branch? 
I see 2 options:

- Force the installation of this branch during installation (mandated by the `setup.py` file) which I have tried and gives me many issues
- Every time we add a function that relies on non-linear-axis branch, we need to add Error handeling (with a note suggesting the user to install the Hyperspy branch instead of the master version).

For now I think the second is better, as it makes installaton easier.

**Comment by jlaehne** [comment]
Yes, I will add a note to the docstring and will see how to appropriately raise an error if the DataAxis object is not available.
