### ISSUE TITLE
signals vs. _signals

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#17]
@dnjohnstone Do you know why in Hyperspy the signal classes are in `_signals`, while we have them in `signals`. Would it make sense to copy the structure here in that aspect?

**Comment by ericpre** [comment]
Since things staring with `_` are considered as private, I believe the idea behind putting  signals in `_signals` is to make these modules private and these are added to the `api` module to make them public: this is what we do when running `import hyperspy.api as hs`. Having an API module allows to explicitly define what is part of the public API or not.
This was behind "my time" as hyperspy contributor so I don't know the details, but @francisco-dlp will of course!
In principle, you can put signals anywhere you want but having a API consistent with other libraries doesn't sounds like a bad idea! As it is at the moment, it looks sensible to me.

**Comment by francisco-dlp** [comment]
@ericpre, you guessed right. The idea was indeed not to expose the real location of the signals code in the pubic API so that changes in there don't break people's scripts and external packages.

**Comment by jlaehne** [comment]
@jordiferrero, I think from the comments above, we can leave it as is.

The idea of LumiSpy is to be an extension of HyperSpy. As such, signals will likely not be called from LumiSpy directly, but as they are registered with HyperSpy the idea is to call them through the HyperSpy API.

It makes sense that we call the folder signals for clarity, but it does not need to be a private folder. I could though do the conversion to `_signals` if that would be of advantage, any opinion @ericpre, @jordiferrero ?

**Comment by ericpre** [comment]
It may be more simple to keep `signals` and tidy up the namespace: currently, everything is imported in lumispy and with time, it can get cluttered.
Also the `load` function and the `roi` module is imported from hyperspy and added to the lumispy namespace, this is not a standard practise in python and can be confusing for users to have the same objects which can be imported from different libraries. For example, pxyem has standardised/simplified its namespace in https://github.com/pyxem/pyxem/pull/704/files and I think it would be good to do something similarly for lumispy.

**Comment by jlaehne** [comment]
Good point, we mirrored the pyxem namespace, so now that it is cleaned up, we should do the same ;-)

I'll give it a try.

**Comment by jlaehne** [comment]
Done with #49.
