### ISSUE TITLE
Release v0.1.1

### ISSUE THREAD

**Issue by ericpre** [LumiSpy/lumispy#81]
What's about making a v0.1.1 release? A new release would fix the [integration test suite](https://github.com/hyperspy/hyperspy-extensions-list/runs/2958026091?check_suite_focus=true) which is failing with lumispy 0.1.0. This will also save me the reception of an email notification every day to tell me that the integration test suite is failing!

**Comment by jlaehne** [comment]
well, the release workflow is failing now: https://github.com/jlaehne/lumispy/runs/2966555151?check_suite_focus=true

**Comment by ericpre** [comment]
Most likely similar to https://github.com/hyperspy/hyperspy/pull/2768#issuecomment-858841975 and https://github.com/hyperspy/hyperspy/commit/6226eabd25a0f703364f6f363fa163585a7f0e82?

**Comment by jlaehne** [comment]
Thanks, it was the same.

**Comment by jlaehne** [comment]
There seems to be a problem with the PyPi secrets: https://github.com/LumiSpy/lumispy/runs/2970813472?check_suite_focus=true

@jordiferrero can you check them? I don't seem to have access to the settings/secrets on the repository.

**Comment by ericpre** [comment]
It seems that this release workflow have [never been used](https://github.com/LumiSpy/lumispy/actions/workflows/release.yml) to upload directly to pypi, which means that it is possible that the secrets are not set correctly in github.

**Comment by jlaehne** [comment]
Yes, the first release was manual. The workflow was added afterwards and has only been tested in my private repo (without upload of course). But in the repo settings, I cannot access the secrets to add them.

**Comment by jlaehne** [comment]
I will be offline for the next month and will not be able to finish up this release, feel free to do so once the secrets are sorted out @jordiferrero and @ericpre 

Process is summarized here: https://github.com/LumiSpy/lumispy/blob/master/releasing_guide.md

**Comment by ericpre** [comment]
@jordiferrero, any chance you can check the secrets?

**Comment by jordiferrero** [comment]
Hi @ericpre and @jlaehne. First of all, sorry for being completely disconnected for the last 1.5 months. 
I really had to finish some project off and I am currently taking a short intermission of my PhD during a summer internship in ... Germany :-) (not Berlin though... @jlaehne).

I will be back fully online in September but by then I will check the last PR and the secrets, as requested. 
I will do that in my free time so I may be a bit more slow.

Anyways, have a good summer break!

**Comment by jordiferrero** [comment]
Hi both,
I have double checked the tokens for pypi and updated them with new ones (TWINE_USER and TWINE_PASSWORD). Can you check if that works?

Otherwise, I have also invited both of you as "owners" of the lumispy pypi project. 
Hopefully you can also create a token from there (in case tokens are user-specific, which they should not according to what I have read).

I hope this is useful. Let me know if I can do anything else.

**Comment by ericpre** [comment]
Thanks @jordiferrero, I had a go and it didn't work:
https://github.com/LumiSpy/lumispy/runs/2970813472?check_suite_focus=true

I can make a token on pypi but I can't set the secrets to this repository, because I don't have the admin right, only write right I think: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository
Can you please give the admin access? Then, I can sort out the token!

**Comment by jlaehne** [comment]
Thanks @ericpre for being quicker ;-)

**Comment by jordiferrero** [comment]
OK. I didn't realise there was a "higher" category than collaborator.
Now the 3 of us should be Admins.
Let me know if you can edit the secrets now.
However, I am starting to think that the problem may be a different one... because the secrets should not depend on the person who is doing a PR (for the release) but the repo one I go months ago should work for all of us.

PS: As far as I can remember, the first release I did manually though the command prompt connecting manually to twine and it worked with the secrets are are now stored.

**Comment by jlaehne** [comment]
The release is out on PyPi: https://pypi.org/project/lumispy/

For some reason Zenodo creates multiple DOIs: https://zenodo.org/search?page=1&size=20&q=conceptrecid:%224640445%22&sort=-version&all_versions=True
- any ideas why? Do we need to correct something in the settings, or was that just because of the failed release runs we had along the way. Can we then clear out the duplicate ones (and the skipped version 0.1.1 altogether)?

**Comment by jlaehne** [comment]
Created PR to update `hyperspy-extensions-list`: https://github.com/hyperspy/hyperspy-extensions-list/pull/14/files

**Comment by jordiferrero** [comment]
> The release is out on PyPi: https://pypi.org/project/lumispy/
> 
> For some reason Zenodo creates multiple DOIs: https://zenodo.org/search?page=1&size=20&q=conceptrecid:%224640445%22&sort=-version&all_versions=True
> 
> * any ideas why? Do we need to correct something in the settings, or was that just because of the failed release runs we had along the way. Can we then clear out the duplicate ones (and the skipped version 0.1.1 altogether)?

THANK YOU! That's great you managed to make it work. Was it done automatically or manually?

The Zenodo is indeed weird. There should only be 1 DOI per release. But it seems like it created a few 0.1.1 DOIs since Aug 19... some bug there. However, I don't think you can delete them (that would defeat the purpose of Zenodo) but I wouldn't worry too much. We should always use the base DOI for referencing anyways.

**Comment by jlaehne** [comment]
> The Zenodo is indeed weird. There should only be 1 DOI per release. But it seems like it created a few 0.1.1 DOIs since Aug 19... some bug there. However, I don't think you can delete them (that would defeat the purpose of Zenodo) but I wouldn't worry too much. We should always use the base DOI for referencing anyways.

As the earliest one is even from June, I guess a new DOI is created automatically every time a tag is pushed to the repo - and as the build then failed a few times, we now have the duplicate ones. But then that should not be a problem in the future now that the issues are sorted out.

**Comment by ericpre** [comment]
Yes, when hitting the various issues, I had to create several release but forgot that a zendo entry would be created for each created release! Not the best, but not a big deal neither.
